name: koicmdlist
version: '1.2'
main: koirdsuzu.koicmdlist.Koicmdlist
api-version: '1.20'
folia-supported: true
authors: [ koirdsuzu ]
commands:
  kcl:
    description: "KCLのヘルプや設定を管理する"
    usage: /kcl [help|reload]
    permission: koicmdlist.kcl.use
    permission-message: You do not have permission to use this command.
    aliases: [koicmdlist]

  fly:
    description: "飛行状態を切り替える"
    usage: /flyで飛行を有効、または無効に出来ます。
    permission: koicmdlist.fly.use
    permission-message: You do not have permission to use this command.

  uuid:
    description: "UUIDを取得"
    usage: /uuidでUUIDを取得
    permission: koicmdlist.uuid.use
    permission-message: You do not have permission to use this command.

  whitekick:
    description: "ホワイトリストに登録されていないプレイヤーをキックする"
    usage: /whitekickでホワリス未登録ユーザーを蹴りホワリスを有効化します。
    permission: koicmdlist.whitekick.use
    permission-message: You do not have permission to use this command.

permissions:
  koicmdlist.*:
    description: koicmdlist All Permissions
    default: op
    children:
      koicmdlist.kcl.*: true
      koicmdlist.fly.*: true
      koicmdlist.uuid.*: true
      koicmdlist.whitekick.*: true

  koicmdlist.kcl.*:
    description: koicmdlist All Permissions
    default: op
    children:
      koicmdlist.kcl.use: true
      koicmdlist.kcl.help: true
      koicmdlist.kcl.reload: true

  koicmdlist.fly.*:
    description: "Fly Admin Command"
    default: op
    children:
      koicmdlist.fly.use: true
      koicmdlist.fly.get: true
      koicmdlist.fly.on: true
      koicmdlist.fly.off: true
      koicmdlist.fly.user: true

  koicmdlist.uuid.*:
    description: "UUID Admin Command"
    default: op
    children:
      koicmdlist.uuid.use: true
      koicmdlist.uuid.get: true

  koicmdlist.whitekick.*:
    description: "ホワイトリスト未登録者キック権限"
    default: op
    children:
      koicmdlist.whitekick.use: true
